import type { Pane, Recipe, Workspace } from "./types";

export const WORKSPACES: Workspace[] = [
  {
    id: "ws-harness",
    name: "harness-ready",
    path: "~/Personal/harness-ready",
    harnesses: ["claude", "cursor", "opencode", "codex", "pi", "bash", "grok"],
  },
  {
    id: "ws-harness-lane-a",
    name: "rebrand · lanes A–B",
    path: "~/Personal/harness-ready",
    parentId: "ws-harness",
    lane: "A–B",
    harnesses: ["grok", "claude"],
  },
  {
    id: "ws-harness-lane-c",
    name: "rebrand · lanes C–D",
    path: "~/Personal/harness-ready",
    parentId: "ws-harness",
    lane: "C–D",
    harnesses: ["grok"],
  },
  {
    id: "ws-agent-teams",
    name: "agent-teams",
    path: "~/Personal/agent-teams",
    harnesses: ["claude", "codex", "commandcode", "grok"],
  },
  {
    id: "ws-playground",
    name: "playground",
    path: "~/scratch/playground",
    harnesses: ["bash", "opencode", "pi"],
  },
];

export const RECIPES: Recipe[] = [
  {
    id: "r-review-trio",
    title: "Review trio",
    summary: "Coordinator + builder + reviewer with path ownership",
    harnesses: ["claude", "codex", "cursor"],
    agents: 3,
    workspaceHint: "harness-ready",
  },
  {
    id: "r-scout-build",
    title: "Scout then build",
    summary: "Read-only scout, then implementer",
    harnesses: ["claude", "opencode"],
    agents: 2,
    workspaceHint: "harness-ready",
  },
  {
    id: "r-solo-bash",
    title: "Solo bash",
    summary: "Single shell pane, max gates",
    harnesses: ["bash"],
    agents: 1,
    workspaceHint: "playground",
  },
];

/** Demo fleet — includes intentional path overlap for conflict resolution demo */
export const DEMO_FLEET: Pane[] = [
  {
    id: "ws83621x0-p0",
    workspaceId: "ws-harness",
    name: "Amber Bison",
    harness: "claude",
    role: "coordinator",
    status: "needs_input",
    branch: "rebrand/harness-ready-mcp",
    worktree: ".agent-teams-worktrees/amber-bison",
    attention: "All lanes committed — report when ready",
    cpu: 12.4,
    memMb: 482,
    lastToolFailure: null,
    queueDepth: 1,
    telemetry: "live",
    gitClean: false,
    ownedPaths: ["docs/**", "core/task/**"],
    pinned: true,
  },
  {
    id: "ws83621x0-p1",
    workspaceId: "ws-harness-lane-a",
    name: "Solar Raven",
    harness: "grok",
    role: "builder",
    status: "working",
    branch: "rebrand-lane1",
    worktree: "/tmp/rebrand-lane1",
    cpu: 28.1,
    memMb: 510,
    lastToolFailure: null,
    queueDepth: 0,
    telemetry: "state_blind",
    gitClean: false,
    ownedPaths: ["core/hooks/**", "core/**"],
  },
  {
    id: "ws83621x0-p2",
    workspaceId: "ws-harness-lane-a",
    name: "Neon Tiger",
    harness: "grok",
    role: "builder",
    status: "working",
    branch: "rebrand-lane2",
    worktree: "/tmp/rebrand-lane2",
    cpu: 22.0,
    memMb: 480,
    queueDepth: 0,
    telemetry: "state_blind",
    gitClean: false,
    // Intentional overlap with Solar Raven for conflict demo
    ownedPaths: ["core/state-adaptor/**", "core/hooks/**"],
  },
  {
    id: "ws83621x0-p3",
    workspaceId: "ws-harness-lane-c",
    name: "Amber Orca",
    harness: "grok",
    role: "builder",
    status: "working",
    branch: "rebrand-lane3",
    worktree: "/tmp/rebrand-lane3",
    cpu: 18.0,
    memMb: 430,
    queueDepth: 0,
    telemetry: "state_blind",
    gitClean: true,
    ownedPaths: ["app/**"],
  },
  {
    id: "ws83621x0-p4",
    workspaceId: "ws-harness-lane-c",
    name: "Amber Raven",
    harness: "grok",
    role: "builder",
    status: "needs_input",
    branch: "rebrand-lane4",
    worktree: "/tmp/rebrand-lane4",
    attention: "Confirm merge order for lane D",
    cpu: 15.0,
    memMb: 400,
    queueDepth: 1,
    telemetry: "state_blind",
    gitClean: false,
    ownedPaths: ["scripts/**"],
  },
  {
    id: "ws83621x0-p5",
    workspaceId: "ws-harness",
    name: "Audit Shell",
    harness: "bash",
    role: "none",
    status: "idle",
    branch: "rebrand/harness-ready-mcp",
    worktree: ".agent-teams-worktrees/audit",
    cpu: 0.2,
    memMb: 40,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
  },
  {
    id: "ws83621x0-p6",
    workspaceId: "ws-harness",
    name: "Scout Map",
    harness: "opencode",
    role: "scout",
    status: "idle",
    branch: "explore",
    worktree: ".agent-teams-worktrees/scout",
    cpu: 1.0,
    memMb: 180,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
  },
  {
    id: "ws83621x0-p7",
    workspaceId: "ws-harness",
    name: "Codex Review",
    harness: "codex",
    role: "reviewer",
    status: "idle",
    branch: "review/pr",
    worktree: ".agent-teams-worktrees/review",
    cpu: 2.0,
    memMb: 220,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
  },
  {
    id: "ws83621x0-p8",
    workspaceId: "ws-harness",
    name: "Pi Probe",
    harness: "pi",
    role: "none",
    status: "idle",
    branch: "probe",
    worktree: ".agent-teams-worktrees/pi",
    cpu: null,
    memMb: null,
    queueDepth: 0,
    telemetry: "state_blind",
    gitClean: true,
  },
  {
    id: "p-06",
    workspaceId: "ws-agent-teams",
    name: "Swarm Lead",
    harness: "claude",
    role: "coordinator",
    status: "working",
    branch: "main",
    worktree: ".agent-teams-worktrees/swarm-lead",
    cpu: 8.2,
    memMb: 390,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
    pinned: true,
  },
  {
    id: "p-07",
    workspaceId: "ws-agent-teams",
    name: "Grok Worker",
    harness: "grok",
    role: "builder",
    status: "needs_input",
    branch: "feat/x",
    worktree: ".agent-teams-worktrees/grok-worker",
    attention: "Confirm API key scope",
    cpu: null,
    memMb: null,
    queueDepth: 1,
    telemetry: "state_blind",
    gitClean: false,
  },
  {
    id: "p-08",
    workspaceId: "ws-agent-teams",
    name: "CmdCode",
    harness: "commandcode",
    role: "builder",
    status: "idle",
    branch: "feat/x",
    worktree: ".agent-teams-worktrees/cmdcode",
    cpu: null,
    memMb: null,
    queueDepth: 0,
    telemetry: "state_blind",
    gitClean: true,
  },
  {
    id: "p-09",
    workspaceId: "ws-playground",
    name: "shell-1",
    harness: "bash",
    role: "none",
    status: "idle",
    branch: "scratch",
    worktree: ".agent-teams-worktrees/shell-1",
    cpu: 0.4,
    memMb: 48,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
  },
  {
    id: "p-10",
    workspaceId: "ws-playground",
    name: "explore",
    harness: "opencode",
    role: "scout",
    status: "working",
    branch: "scratch",
    worktree: ".agent-teams-worktrees/explore",
    cpu: 6.1,
    memMb: 280,
    queueDepth: 0,
    telemetry: "live",
    gitClean: true,
  },
];

export const MEMORY_NODES = [
  { id: "n1", label: "auth gates", kind: "decision" as const },
  { id: "n2", label: "spawn contract", kind: "fact" as const },
  { id: "n3", label: "open: liveness", kind: "open" as const },
  { id: "n4", label: "worktree isolation", kind: "fact" as const },
  { id: "n5", label: "sub-linear pack", kind: "note" as const },
];

export const MEMORY_EDGES: [string, string][] = [
  ["n1", "n2"],
  ["n2", "n3"],
  ["n2", "n4"],
  ["n4", "n5"],
];
